// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shoppe.Persistence.Context;

#nullable disable

namespace Shoppe.Persistence.Migrations
{
    [DbContext(typeof(ShoppeDbContext))]
    [Migration("20241122133532_mig_1")]
    partial class mig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogBlogCategory", b =>
                {
                    b.Property<Guid>("BlogsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BlogsId", "CategoriesId");

                    b.HasIndex("CategoriesId");

                    b.ToTable("BlogBlogCategory");
                });

            modelBuilder.Entity("BlogBlogTag", b =>
                {
                    b.Property<Guid>("BlogsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BlogsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("BlogBlogTag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "admin-user-id",
                            RoleId = "admin-role-id"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProductProductCategory", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("ProductProductCategory");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.About", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasAnnotation("RegexPattern", "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasAnnotation("RegexPattern", "^\\+?\\d{1,3}?[-.●]?\\(?\\d{1,4}?\\)?[-.●]?\\d{1,4}[-.●]?\\d{1,9}$");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("About");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dd37583b-9c78-4159-a1e7-ccdc6a8be9eb"),
                            CreatedAt = new DateTime(2024, 11, 22, 13, 35, 31, 796, DateTimeKind.Utc).AddTicks(4750),
                            Description = "Who we are and why we do what we do!",
                            Email = "contact@shoppe.com",
                            Name = "Shoppe",
                            Phone = "123-456-7890",
                            Title = ""
                        });
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasDiscriminator<string>("AddressType").HasValue("Address");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Basket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CouponId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("UserId");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.BasketItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BasketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("ProductId");

                    b.ToTable("BasketItems", t =>
                        {
                            t.HasCheckConstraint("CK_BasketItem_Quantity", "Quantity >= 0");
                        });
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Blog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("BlogCoverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("BlogCoverId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasDiscriminator<string>("Type").HasValue("Category");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Contacts.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAnswered")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasDiscriminator<string>("Type").HasValue("Contact");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxUsage")
                        .HasColumnType("int");

                    b.Property<decimal>("MinimumOrderAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Discounts", t =>
                        {
                            t.HasCheckConstraint("CK_Discount_DiscountPercentage", "[DiscountPercentage] > 0 AND [DiscountPercentage] <= 100");
                        });
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.DiscountCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DiscountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("CategoryId", "DiscountId")
                        .IsUnique();

                    b.ToTable("DiscountCategory");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.DiscountProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DiscountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("ProductId", "DiscountId")
                        .IsUnique();

                    b.ToTable("DiscountProduct");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.ApplicationFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Storage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ApplicationFiles");

                    b.HasDiscriminator().HasValue("ApplicationFile");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-role-id",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        });
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-user-id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "80d3fabe-7f50-467d-a6ce-ed9972bafe91",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nurlancreus@example.com",
                            EmailConfirmed = false,
                            FirstName = "Nurlan",
                            IsActive = false,
                            LastName = "Shukurov",
                            LockoutEnabled = false,
                            NormalizedEmail = "NURLANCREUS@EXAMPLE.COM",
                            NormalizedUserName = "NURLANCREUS",
                            PasswordHash = "AQAAAAIAAYagAAAAENcMe5rfCTSwr8qIdy5PFPjlxBWmZmWFJSxLLa4YKuCB5OjOrDuKyVKvFWIgaSDVkg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "40bb6371-88b6-49f9-a615-cf866f023fe7",
                            TwoFactorEnabled = false,
                            UserName = "nurlancreus"
                        });
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillingAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<Guid?>("CouponId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShippingAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BillingAddressId");

                    b.HasIndex("CouponId");

                    b.HasIndex("ShippingAddressId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid>("ProductDetailsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.ProductDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Colors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Materials")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.ProductDimension", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ProductDimensions");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Reactions.Reaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reactions");

                    b.HasDiscriminator<string>("EntityType").HasValue("Reaction");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Replies.Reply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Depth")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReplierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ReplierId");

                    b.ToTable("Replies", t =>
                        {
                            t.HasCheckConstraint("CK_Reply_Depth", "[Depth] >= 0 AND [Depth] <= 3");
                        });

                    b.HasDiscriminator<string>("Type").HasValue("Reply");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Reviews.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Reviews");

                    b.HasDiscriminator<string>("Type").HasValue("Review");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Slide", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Order")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("SliderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SliderId");

                    b.ToTable("Slides", t =>
                        {
                            t.HasCheckConstraint("CK_Slide_Order", "[Order] >= 0 AND [Order] <= 255");
                        });
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Sliders.Slider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasDiscriminator<string>("Type").HasValue("Slider");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.SocialMediaLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AboutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SocialPlatform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AboutId");

                    b.ToTable("SocialMediaLinks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e6d4953c-88d2-4320-a661-3af03ddcee1c"),
                            AboutId = new Guid("dd37583b-9c78-4159-a1e7-ccdc6a8be9eb"),
                            CreatedAt = new DateTime(2024, 11, 22, 13, 35, 31, 828, DateTimeKind.Utc).AddTicks(2759),
                            SocialPlatform = "Facebook",
                            URL = "https://facebook.com/shoppe"
                        },
                        new
                        {
                            Id = new Guid("bcb14f6b-2221-466e-aa4b-bb5379b1828c"),
                            AboutId = new Guid("dd37583b-9c78-4159-a1e7-ccdc6a8be9eb"),
                            CreatedAt = new DateTime(2024, 11, 22, 13, 35, 31, 828, DateTimeKind.Utc).AddTicks(2764),
                            SocialPlatform = "X",
                            URL = "https://x.com/shoppe"
                        },
                        new
                        {
                            Id = new Guid("08779f9f-b74e-4cf0-a3d0-a39e62db01e2"),
                            AboutId = new Guid("dd37583b-9c78-4159-a1e7-ccdc6a8be9eb"),
                            CreatedAt = new DateTime(2024, 11, 22, 13, 35, 31, 828, DateTimeKind.Utc).AddTicks(2767),
                            SocialPlatform = "Instagram",
                            URL = "https://instagram.com/shoppe"
                        },
                        new
                        {
                            Id = new Guid("88290fc0-78ab-4f71-9367-250d3e17b08b"),
                            AboutId = new Guid("dd37583b-9c78-4159-a1e7-ccdc6a8be9eb"),
                            CreatedAt = new DateTime(2024, 11, 22, 13, 35, 31, 828, DateTimeKind.Utc).AddTicks(2770),
                            SocialPlatform = "Youtube",
                            URL = "https://youtube.com/shoppe"
                        });
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasDiscriminator<string>("Type").HasValue("Tag");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.BillingAddress", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Address");

                    b.HasDiscriminator().HasValue("Billing");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.ShippingAddress", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Address");

                    b.HasDiscriminator().HasValue("Delivery");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Categories.BlogCategory", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Categories.Category");

                    b.HasDiscriminator().HasValue("Blog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("61b1b6f4-5300-4503-a008-424081233a62"),
                            CreatedAt = new DateTime(2024, 11, 22, 13, 35, 31, 798, DateTimeKind.Utc).AddTicks(2760),
                            Description = "Tips on how to take care of your jewelry",
                            Name = "Jewelry Care",
                            Type = "Blog"
                        },
                        new
                        {
                            Id = new Guid("ee9c04e4-3bf5-4fb3-ac4f-e2b8e66d40b6"),
                            CreatedAt = new DateTime(2024, 11, 22, 13, 35, 31, 798, DateTimeKind.Utc).AddTicks(2765),
                            Description = "Updates on the latest jewelry trends",
                            Name = "Latest Trends",
                            Type = "Blog"
                        },
                        new
                        {
                            Id = new Guid("cc3471d3-1475-44b0-8f4f-b7bc53ccd956"),
                            CreatedAt = new DateTime(2024, 11, 22, 13, 35, 31, 798, DateTimeKind.Utc).AddTicks(2781),
                            Description = "Learn about different gemstones and their meanings",
                            Name = "Gemstone Guide",
                            Type = "Blog"
                        },
                        new
                        {
                            Id = new Guid("b7dc85dd-626f-4463-96b2-4245fe264317"),
                            CreatedAt = new DateTime(2024, 11, 22, 13, 35, 31, 798, DateTimeKind.Utc).AddTicks(2784),
                            Description = "Jewelry gift ideas for various occasions",
                            Name = "Gift Ideas",
                            Type = "Blog"
                        },
                        new
                        {
                            Id = new Guid("395f86da-00d3-41cf-920c-1710dbf9c9cb"),
                            CreatedAt = new DateTime(2024, 11, 22, 13, 35, 31, 798, DateTimeKind.Utc).AddTicks(2786),
                            Description = "Guides and inspiration for making your own jewelry",
                            Name = "DIY Jewelry",
                            Type = "Blog"
                        });
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Categories.ProductCategory", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Categories.Category");

                    b.HasDiscriminator().HasValue("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaf65213-624b-4d1a-a2bf-1e0db70174fc"),
                            CreatedAt = new DateTime(2024, 11, 22, 13, 35, 31, 821, DateTimeKind.Utc).AddTicks(6495),
                            Description = "Elegant and modern necklaces",
                            Name = "Necklaces",
                            Type = "Product"
                        },
                        new
                        {
                            Id = new Guid("d1b47eff-ba1c-4bb2-9ba3-e8d9ae7c401f"),
                            CreatedAt = new DateTime(2024, 11, 22, 13, 35, 31, 821, DateTimeKind.Utc).AddTicks(6513),
                            Description = "Stylish earrings for all occasions",
                            Name = "Earrings",
                            Type = "Product"
                        },
                        new
                        {
                            Id = new Guid("f921097c-be86-4efc-9e78-f3f7b167118a"),
                            CreatedAt = new DateTime(2024, 11, 22, 13, 35, 31, 821, DateTimeKind.Utc).AddTicks(6516),
                            Description = "Beautiful bracelets in various styles",
                            Name = "Bracelets",
                            Type = "Product"
                        },
                        new
                        {
                            Id = new Guid("e93de8ad-3b6b-41a7-b373-cc708129fafa"),
                            CreatedAt = new DateTime(2024, 11, 22, 13, 35, 31, 821, DateTimeKind.Utc).AddTicks(6519),
                            Description = "Rings for engagement, fashion, and more",
                            Name = "Rings",
                            Type = "Product"
                        },
                        new
                        {
                            Id = new Guid("84867f4d-9a91-4797-9231-6ea84df162bf"),
                            CreatedAt = new DateTime(2024, 11, 22, 13, 35, 31, 821, DateTimeKind.Utc).AddTicks(6522),
                            Description = "Unique brooches to complement any outfit",
                            Name = "Brooches",
                            Type = "Product"
                        });
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Contacts.RegisteredContact", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Contacts.Contact");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("Registered");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Contacts.UnRegisteredContact", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Contacts.Contact");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Unregistered");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.ContentImageFile", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Files.ApplicationFile");

                    b.HasDiscriminator().HasValue("ContentImageFile");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.ImageFile", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Files.ApplicationFile");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("ImageFile");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.SlideImageFile", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Files.ApplicationFile");

                    b.Property<Guid>("SlideId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("SlideId")
                        .IsUnique()
                        .HasFilter("[SlideId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("SlideImageFile");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Reactions.BlogReaction", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Reactions.Reaction");

                    b.Property<Guid>("BlogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlogReactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("BlogId");

                    b.HasIndex("UserId", "BlogId")
                        .IsUnique()
                        .HasFilter("[BlogId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Blog");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Reactions.ReplyReaction", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Reactions.Reaction");

                    b.Property<Guid>("ReplyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReplyReactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("ReplyId");

                    b.HasIndex("UserId", "ReplyId")
                        .IsUnique()
                        .HasFilter("[ReplyId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Reply");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Replies.BlogReply", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Replies.Reply");

                    b.Property<Guid>("BlogId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("BlogId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Reply_Depth", "[Depth] >= 0 AND [Depth] <= 3");
                        });

                    b.HasDiscriminator().HasValue("Blog");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Reviews.ProductReview", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Reviews.Review");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ProductId");

                    b.HasDiscriminator().HasValue("Product");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Sliders.HeroSlider", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Sliders.Slider");

                    b.HasDiscriminator().HasValue("Hero");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Tags.BlogTag", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Tags.Tag");

                    b.HasDiscriminator().HasValue("Blog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ecba83f0-f1da-42af-be2a-37d0b79b5cd8"),
                            CreatedAt = new DateTime(2024, 11, 22, 13, 35, 31, 814, DateTimeKind.Utc).AddTicks(4852),
                            Name = "Fashion",
                            Type = "Blog"
                        },
                        new
                        {
                            Id = new Guid("d484e0a1-68a3-4548-b85c-c1c31d044789"),
                            CreatedAt = new DateTime(2024, 11, 22, 13, 35, 31, 814, DateTimeKind.Utc).AddTicks(4860),
                            Name = "Jewelry Care",
                            Type = "Blog"
                        },
                        new
                        {
                            Id = new Guid("2341d635-4e44-4861-9776-ce7975ae2fb7"),
                            CreatedAt = new DateTime(2024, 11, 22, 13, 35, 31, 814, DateTimeKind.Utc).AddTicks(4864),
                            Name = "Gemstones",
                            Type = "Blog"
                        },
                        new
                        {
                            Id = new Guid("c5e99232-8dbc-4cf0-89ad-dc86accec705"),
                            CreatedAt = new DateTime(2024, 11, 22, 13, 35, 31, 814, DateTimeKind.Utc).AddTicks(4868),
                            Name = "DIY Jewelry",
                            Type = "Blog"
                        },
                        new
                        {
                            Id = new Guid("6e29d249-3d4f-4056-8576-9152ca3bbaeb"),
                            CreatedAt = new DateTime(2024, 11, 22, 13, 35, 31, 814, DateTimeKind.Utc).AddTicks(4871),
                            Name = "Trends",
                            Type = "Blog"
                        });
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.AboutContentImageFile", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Files.ContentImageFile");

                    b.Property<Guid>("AboutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("AboutId");

                    b.HasDiscriminator().HasValue("AboutContentImageFile");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.BlogContentImageFile", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Files.ContentImageFile");

                    b.Property<Guid?>("BlogId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("BlogId");

                    b.HasDiscriminator().HasValue("BlogContentImageFile");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.ProductImageFile", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Files.ImageFile");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ProductId", "IsMain")
                        .IsUnique()
                        .HasFilter("[ProductId] IS NOT NULL AND [IsMain] = 1");

                    b.HasDiscriminator().HasValue("ProductImageFile");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.UserProfileImageFile", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Files.ImageFile");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("UserId", "IsMain")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL AND [IsMain] = 1");

                    b.HasDiscriminator().HasValue("UserProfileImageFile");
                });

            modelBuilder.Entity("BlogBlogCategory", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Blog", null)
                        .WithMany()
                        .HasForeignKey("BlogsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoppe.Domain.Entities.Categories.BlogCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlogBlogTag", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Blog", null)
                        .WithMany()
                        .HasForeignKey("BlogsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoppe.Domain.Entities.Tags.BlogTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductProductCategory", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Categories.ProductCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoppe.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Basket", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Coupon", "Coupon")
                        .WithMany("Baskets")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationUser", "User")
                        .WithMany("Baskets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.BasketItem", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Basket", "Basket")
                        .WithMany("Items")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoppe.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Blog", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationUser", "Author")
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoppe.Domain.Entities.Files.BlogContentImageFile", "BlogCoverImageFile")
                        .WithMany("Blogs")
                        .HasForeignKey("BlogCoverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("BlogCoverImageFile");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.DiscountCategory", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Categories.ProductCategory", "Category")
                        .WithMany("DiscountMappings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoppe.Domain.Entities.Discount", "Discount")
                        .WithMany("CategoryMappings")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Discount");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.DiscountProduct", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Discount", "Discount")
                        .WithMany("ProductMappings")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoppe.Domain.Entities.Product", "Product")
                        .WithMany("DiscountMappings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Order", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.BillingAddress", "BillingAddress")
                        .WithMany("Orders")
                        .HasForeignKey("BillingAddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Shoppe.Domain.Entities.Coupon", "Coupon")
                        .WithMany("Orders")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Shoppe.Domain.Entities.Basket", "Basket")
                        .WithOne("Order")
                        .HasForeignKey("Shoppe.Domain.Entities.Order", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoppe.Domain.Entities.ShippingAddress", "ShippingAddress")
                        .WithMany("Orders")
                        .HasForeignKey("ShippingAddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("BillingAddress");

                    b.Navigation("Coupon");

                    b.Navigation("ShippingAddress");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("Shoppe.Domain.Entities.Payment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.ProductDetails", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Product", "Product")
                        .WithOne("ProductDetails")
                        .HasForeignKey("Shoppe.Domain.Entities.ProductDetails", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.ProductDimension", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.ProductDetails", "ProductDetails")
                        .WithOne("Dimension")
                        .HasForeignKey("Shoppe.Domain.Entities.ProductDimension", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductDetails");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Reactions.Reaction", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationUser", "User")
                        .WithMany("Reactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Replies.Reply", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Replies.Reply", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationUser", "Replier")
                        .WithMany("Replies")
                        .HasForeignKey("ReplierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Replier");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Reviews.Review", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationUser", "Reviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Slide", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Sliders.Slider", "Slider")
                        .WithMany("Slides")
                        .HasForeignKey("SliderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Slider");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.SocialMediaLink", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.About", null)
                        .WithMany("SocialMediaLinks")
                        .HasForeignKey("AboutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Contacts.RegisteredContact", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.SlideImageFile", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Slide", "Slide")
                        .WithOne("SlideImageFile")
                        .HasForeignKey("Shoppe.Domain.Entities.Files.SlideImageFile", "SlideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Slide");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Reactions.BlogReaction", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Blog", "Blog")
                        .WithMany("Reactions")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Reactions.ReplyReaction", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Replies.Reply", "Reply")
                        .WithMany("Reactions")
                        .HasForeignKey("ReplyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Reply");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Replies.BlogReply", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Blog", "Blog")
                        .WithMany("Replies")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Reviews.ProductReview", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.AboutContentImageFile", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.About", "About")
                        .WithMany("ContentImages")
                        .HasForeignKey("AboutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("About");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.BlogContentImageFile", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Blog", null)
                        .WithMany("ContentImages")
                        .HasForeignKey("BlogId");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.ProductImageFile", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Product", "Product")
                        .WithMany("ProductImageFiles")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.UserProfileImageFile", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationUser", "User")
                        .WithMany("ProfilePictureFiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.About", b =>
                {
                    b.Navigation("ContentImages");

                    b.Navigation("SocialMediaLinks");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Basket", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Blog", b =>
                {
                    b.Navigation("ContentImages");

                    b.Navigation("Reactions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Coupon", b =>
                {
                    b.Navigation("Baskets");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Discount", b =>
                {
                    b.Navigation("CategoryMappings");

                    b.Navigation("ProductMappings");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Baskets");

                    b.Navigation("Blogs");

                    b.Navigation("ProfilePictureFiles");

                    b.Navigation("Reactions");

                    b.Navigation("Replies");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Order", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Product", b =>
                {
                    b.Navigation("DiscountMappings");

                    b.Navigation("ProductDetails")
                        .IsRequired();

                    b.Navigation("ProductImageFiles");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.ProductDetails", b =>
                {
                    b.Navigation("Dimension")
                        .IsRequired();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Replies.Reply", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Slide", b =>
                {
                    b.Navigation("SlideImageFile")
                        .IsRequired();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Sliders.Slider", b =>
                {
                    b.Navigation("Slides");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.BillingAddress", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.ShippingAddress", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Categories.ProductCategory", b =>
                {
                    b.Navigation("DiscountMappings");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.BlogContentImageFile", b =>
                {
                    b.Navigation("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
