// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shoppe.Persistence.Context;

#nullable disable

namespace Shoppe.Persistence.Migrations
{
    [DbContext(typeof(ShoppeDbContext))]
    [Migration("20241114112951_mig_4")]
    partial class mig_4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogBlogCategory", b =>
                {
                    b.Property<Guid>("BlogsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BlogsId", "CategoriesId");

                    b.HasIndex("CategoriesId");

                    b.ToTable("BlogBlogCategory");
                });

            modelBuilder.Entity("BlogBlogTag", b =>
                {
                    b.Property<Guid>("BlogsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BlogsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("BlogBlogTag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "admin-user-id",
                            RoleId = "admin-role-id"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProductProductCategory", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("ProductProductCategory");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.About", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasAnnotation("RegexPattern", "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasAnnotation("RegexPattern", "^\\+?\\d{1,3}?[-.●]?\\(?\\d{1,4}?\\)?[-.●]?\\d{1,4}[-.●]?\\d{1,9}$");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("About");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dd37583b-9c78-4159-a1e7-ccdc6a8be9eb"),
                            CreatedAt = new DateTime(2024, 11, 14, 11, 29, 50, 389, DateTimeKind.Utc).AddTicks(3952),
                            Description = "Who we are and why we do what we do!",
                            Email = "contact@shoppe.com",
                            Name = "Shoppe",
                            Phone = "123-456-7890",
                            Title = ""
                        });
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasDiscriminator<string>("AddressType").HasValue("Address");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Basket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CouponId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("UserId");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.BasketItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BasketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("ProductId");

                    b.ToTable("BasketItems", t =>
                        {
                            t.HasCheckConstraint("CK_BasketItem_Quantity", "Quantity >= 0");
                        });
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Blog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("BlogCoverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("BlogCoverId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasDiscriminator<string>("Type").HasValue("Category");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxUsage")
                        .HasColumnType("int");

                    b.Property<decimal>("MinimumOrderAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Discounts", t =>
                        {
                            t.HasCheckConstraint("CK_Discount_DiscountPercentage", "[DiscountPercentage] > 0 AND [DiscountPercentage] <= 100");
                        });
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.DiscountCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DiscountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("CategoryId", "DiscountId")
                        .IsUnique();

                    b.ToTable("DiscountCategory");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.DiscountProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DiscountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("ProductId", "DiscountId")
                        .IsUnique();

                    b.ToTable("DiscountProduct");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.ApplicationFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Storage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ApplicationFiles");

                    b.HasDiscriminator().HasValue("ApplicationFile");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-role-id",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        });
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-user-id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c9377adc-b946-4d5a-9125-b96294affa28",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nurlancreus@example.com",
                            EmailConfirmed = false,
                            FirstName = "Nurlan",
                            IsActive = false,
                            LastName = "Shukurov",
                            LockoutEnabled = false,
                            NormalizedEmail = "NURLANCREUS@EXAMPLE.COM",
                            NormalizedUserName = "NURLANCREUS",
                            PasswordHash = "AQAAAAIAAYagAAAAEGwZCfJMGAZHLQw7ip4WOP0zQNm2bio6evVleS0pdbJ8uHrjBT1tA+G/CoW2Fd1lxA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e3bf8171-feb6-4474-b346-0b9b5dfce0c2",
                            TwoFactorEnabled = false,
                            UserName = "nurlancreus"
                        });
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillingAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<Guid?>("CouponId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShippingAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BillingAddressId");

                    b.HasIndex("CouponId");

                    b.HasIndex("ShippingAddressId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid>("ProductDetailsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.ProductDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Colors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Materials")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.ProductDimension", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ProductDimensions");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Reactions.Reaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reactions");

                    b.HasDiscriminator<string>("EntityType").HasValue("Reaction");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Replies.Reply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParentReplyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReplierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentReplyId");

                    b.HasIndex("ReplierId");

                    b.ToTable("Replies");

                    b.HasDiscriminator<string>("Type").HasValue("Reply");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Reviews.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Reviews");

                    b.HasDiscriminator<string>("Type").HasValue("Review");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Slide", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Order")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("SliderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SliderId");

                    b.ToTable("Slides", t =>
                        {
                            t.HasCheckConstraint("CK_Slide_Order", "[Order] >= 0 AND [Order] <= 255");
                        });
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Sliders.Slider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasDiscriminator<string>("Type").HasValue("Slider");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.SocialMediaLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AboutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SocialPlatform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AboutId");

                    b.ToTable("SocialMediaLinks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1aff70e-bdb8-403b-a976-9e8f1ab11ac5"),
                            AboutId = new Guid("dd37583b-9c78-4159-a1e7-ccdc6a8be9eb"),
                            CreatedAt = new DateTime(2024, 11, 14, 11, 29, 50, 405, DateTimeKind.Utc).AddTicks(5927),
                            SocialPlatform = "Facebook",
                            URL = "https://facebook.com/shoppe"
                        },
                        new
                        {
                            Id = new Guid("e12a4c6b-eabb-48d4-9da9-de9393ada406"),
                            AboutId = new Guid("dd37583b-9c78-4159-a1e7-ccdc6a8be9eb"),
                            CreatedAt = new DateTime(2024, 11, 14, 11, 29, 50, 405, DateTimeKind.Utc).AddTicks(5932),
                            SocialPlatform = "X",
                            URL = "https://x.com/shoppe"
                        },
                        new
                        {
                            Id = new Guid("a7477752-518e-4de6-93d9-b2e99f7a225b"),
                            AboutId = new Guid("dd37583b-9c78-4159-a1e7-ccdc6a8be9eb"),
                            CreatedAt = new DateTime(2024, 11, 14, 11, 29, 50, 405, DateTimeKind.Utc).AddTicks(5935),
                            SocialPlatform = "Instagram",
                            URL = "https://instagram.com/shoppe"
                        },
                        new
                        {
                            Id = new Guid("6b53913a-8e9d-46de-ad51-56229baf5182"),
                            AboutId = new Guid("dd37583b-9c78-4159-a1e7-ccdc6a8be9eb"),
                            CreatedAt = new DateTime(2024, 11, 14, 11, 29, 50, 405, DateTimeKind.Utc).AddTicks(5938),
                            SocialPlatform = "Youtube",
                            URL = "https://youtube.com/shoppe"
                        });
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasDiscriminator<string>("Type").HasValue("Tag");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.BillingAddress", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Address");

                    b.HasDiscriminator().HasValue("Billing");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.ShippingAddress", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Address");

                    b.HasDiscriminator().HasValue("Delivery");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Categories.BlogCategory", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Categories.Category");

                    b.HasDiscriminator().HasValue("Blog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fa9cf34e-7f8f-4d09-aef2-39db52fd44f4"),
                            CreatedAt = new DateTime(2024, 11, 14, 11, 29, 50, 391, DateTimeKind.Utc).AddTicks(1564),
                            Description = "Tips on how to take care of your jewelry",
                            Name = "Jewelry Care",
                            Type = "Blog"
                        },
                        new
                        {
                            Id = new Guid("0a9d90d2-c1db-4ebd-b629-28293a72d5c9"),
                            CreatedAt = new DateTime(2024, 11, 14, 11, 29, 50, 391, DateTimeKind.Utc).AddTicks(1569),
                            Description = "Updates on the latest jewelry trends",
                            Name = "Latest Trends",
                            Type = "Blog"
                        },
                        new
                        {
                            Id = new Guid("a5e7f063-353d-4d51-9bf3-43144e359712"),
                            CreatedAt = new DateTime(2024, 11, 14, 11, 29, 50, 391, DateTimeKind.Utc).AddTicks(1572),
                            Description = "Learn about different gemstones and their meanings",
                            Name = "Gemstone Guide",
                            Type = "Blog"
                        },
                        new
                        {
                            Id = new Guid("2a6a77d3-23a3-4d73-870d-c9be8b9d0555"),
                            CreatedAt = new DateTime(2024, 11, 14, 11, 29, 50, 391, DateTimeKind.Utc).AddTicks(1575),
                            Description = "Jewelry gift ideas for various occasions",
                            Name = "Gift Ideas",
                            Type = "Blog"
                        },
                        new
                        {
                            Id = new Guid("a010490d-2e18-4274-9bf9-2d5b4b5efa79"),
                            CreatedAt = new DateTime(2024, 11, 14, 11, 29, 50, 391, DateTimeKind.Utc).AddTicks(1578),
                            Description = "Guides and inspiration for making your own jewelry",
                            Name = "DIY Jewelry",
                            Type = "Blog"
                        });
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Categories.ProductCategory", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Categories.Category");

                    b.HasDiscriminator().HasValue("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ce96dc00-381b-4b1f-baba-8aac959d0858"),
                            CreatedAt = new DateTime(2024, 11, 14, 11, 29, 50, 399, DateTimeKind.Utc).AddTicks(7095),
                            Description = "Elegant and modern necklaces",
                            Name = "Necklaces",
                            Type = "Product"
                        },
                        new
                        {
                            Id = new Guid("6f719a55-ea0c-4334-be0b-658de44961df"),
                            CreatedAt = new DateTime(2024, 11, 14, 11, 29, 50, 399, DateTimeKind.Utc).AddTicks(7100),
                            Description = "Stylish earrings for all occasions",
                            Name = "Earrings",
                            Type = "Product"
                        },
                        new
                        {
                            Id = new Guid("b6f2a0d3-023b-43d8-8584-67a0177eb70d"),
                            CreatedAt = new DateTime(2024, 11, 14, 11, 29, 50, 399, DateTimeKind.Utc).AddTicks(7103),
                            Description = "Beautiful bracelets in various styles",
                            Name = "Bracelets",
                            Type = "Product"
                        },
                        new
                        {
                            Id = new Guid("37ec125a-cb3e-4633-aebe-765f14ad3ffb"),
                            CreatedAt = new DateTime(2024, 11, 14, 11, 29, 50, 399, DateTimeKind.Utc).AddTicks(7107),
                            Description = "Rings for engagement, fashion, and more",
                            Name = "Rings",
                            Type = "Product"
                        },
                        new
                        {
                            Id = new Guid("cf01d319-7c54-4e8b-a0ae-4f267be50eac"),
                            CreatedAt = new DateTime(2024, 11, 14, 11, 29, 50, 399, DateTimeKind.Utc).AddTicks(7110),
                            Description = "Unique brooches to complement any outfit",
                            Name = "Brooches",
                            Type = "Product"
                        });
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.ContentImageFile", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Files.ApplicationFile");

                    b.HasDiscriminator().HasValue("ContentImageFile");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.ImageFile", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Files.ApplicationFile");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("ImageFile");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.SlideImageFile", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Files.ApplicationFile");

                    b.Property<Guid>("SlideId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("SlideId")
                        .IsUnique()
                        .HasFilter("[SlideId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("SlideImageFile");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Reactions.BlogReaction", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Reactions.Reaction");

                    b.Property<Guid>("BlogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlogReactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("BlogId");

                    b.HasIndex("UserId", "BlogId")
                        .IsUnique()
                        .HasFilter("[BlogId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Blog");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Reactions.ReplyReaction", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Reactions.Reaction");

                    b.Property<Guid>("ReplyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReplyReactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("ReplyId");

                    b.HasIndex("UserId", "ReplyId")
                        .IsUnique()
                        .HasFilter("[ReplyId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Reply");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Replies.BlogReply", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Replies.Reply");

                    b.Property<Guid>("BlogId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("BlogId");

                    b.HasDiscriminator().HasValue("Blog");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Reviews.ProductReview", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Reviews.Review");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ProductId");

                    b.HasDiscriminator().HasValue("Product");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Sliders.HeroSlider", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Sliders.Slider");

                    b.HasDiscriminator().HasValue("Hero");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Tags.BlogTag", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Tags.Tag");

                    b.HasDiscriminator().HasValue("Blog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a4ed4bd6-2a5d-4132-a7b5-f6f1c939e69a"),
                            CreatedAt = new DateTime(2024, 11, 14, 11, 29, 50, 394, DateTimeKind.Utc).AddTicks(2935),
                            Name = "Fashion",
                            Type = "Blog"
                        },
                        new
                        {
                            Id = new Guid("d968fa55-9fd3-420e-aee4-a1388694729e"),
                            CreatedAt = new DateTime(2024, 11, 14, 11, 29, 50, 394, DateTimeKind.Utc).AddTicks(2939),
                            Name = "Jewelry Care",
                            Type = "Blog"
                        },
                        new
                        {
                            Id = new Guid("3ed6467f-ce3d-4d3a-a75d-2a6e9bd215bc"),
                            CreatedAt = new DateTime(2024, 11, 14, 11, 29, 50, 394, DateTimeKind.Utc).AddTicks(2956),
                            Name = "Gemstones",
                            Type = "Blog"
                        },
                        new
                        {
                            Id = new Guid("291b385f-79c8-4dbf-96b2-64ef0aeb74e3"),
                            CreatedAt = new DateTime(2024, 11, 14, 11, 29, 50, 394, DateTimeKind.Utc).AddTicks(2959),
                            Name = "DIY Jewelry",
                            Type = "Blog"
                        },
                        new
                        {
                            Id = new Guid("b7954637-d3ca-4d8f-9085-9a280f167d64"),
                            CreatedAt = new DateTime(2024, 11, 14, 11, 29, 50, 394, DateTimeKind.Utc).AddTicks(2961),
                            Name = "Trends",
                            Type = "Blog"
                        });
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.AboutContentImageFile", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Files.ContentImageFile");

                    b.Property<Guid>("AboutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("AboutId");

                    b.HasDiscriminator().HasValue("AboutContentImageFile");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.BlogContentImageFile", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Files.ContentImageFile");

                    b.Property<Guid?>("BlogId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("BlogId");

                    b.HasDiscriminator().HasValue("BlogContentImageFile");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.ProductImageFile", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Files.ImageFile");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ProductId", "IsMain")
                        .IsUnique()
                        .HasFilter("[ProductId] IS NOT NULL AND [IsMain] = 1");

                    b.HasDiscriminator().HasValue("ProductImageFile");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.UserProfileImageFile", b =>
                {
                    b.HasBaseType("Shoppe.Domain.Entities.Files.ImageFile");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("UserId", "IsMain")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL AND [IsMain] = 1");

                    b.HasDiscriminator().HasValue("UserProfileImageFile");
                });

            modelBuilder.Entity("BlogBlogCategory", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Blog", null)
                        .WithMany()
                        .HasForeignKey("BlogsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoppe.Domain.Entities.Categories.BlogCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlogBlogTag", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Blog", null)
                        .WithMany()
                        .HasForeignKey("BlogsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoppe.Domain.Entities.Tags.BlogTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductProductCategory", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Categories.ProductCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoppe.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Basket", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Coupon", "Coupon")
                        .WithMany("Baskets")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationUser", "User")
                        .WithMany("Baskets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.BasketItem", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Basket", "Basket")
                        .WithMany("Items")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoppe.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Blog", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationUser", "Author")
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoppe.Domain.Entities.Files.BlogContentImageFile", "BlogCoverImageFile")
                        .WithMany("Blogs")
                        .HasForeignKey("BlogCoverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("BlogCoverImageFile");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.DiscountCategory", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Categories.ProductCategory", "Category")
                        .WithMany("DiscountMappings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoppe.Domain.Entities.Discount", "Discount")
                        .WithMany("CategoryMappings")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Discount");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.DiscountProduct", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Discount", "Discount")
                        .WithMany("ProductMappings")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoppe.Domain.Entities.Product", "Product")
                        .WithMany("DiscountMappings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Order", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.BillingAddress", "BillingAddress")
                        .WithMany("Orders")
                        .HasForeignKey("BillingAddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Shoppe.Domain.Entities.Coupon", "Coupon")
                        .WithMany("Orders")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Shoppe.Domain.Entities.Basket", "Basket")
                        .WithOne("Order")
                        .HasForeignKey("Shoppe.Domain.Entities.Order", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoppe.Domain.Entities.ShippingAddress", "ShippingAddress")
                        .WithMany("Orders")
                        .HasForeignKey("ShippingAddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("BillingAddress");

                    b.Navigation("Coupon");

                    b.Navigation("ShippingAddress");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("Shoppe.Domain.Entities.Payment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.ProductDetails", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Product", "Product")
                        .WithOne("ProductDetails")
                        .HasForeignKey("Shoppe.Domain.Entities.ProductDetails", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.ProductDimension", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.ProductDetails", "ProductDetails")
                        .WithOne("Dimension")
                        .HasForeignKey("Shoppe.Domain.Entities.ProductDimension", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductDetails");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Reactions.Reaction", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationUser", "User")
                        .WithMany("Reactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Replies.Reply", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Replies.Reply", "ParentReply")
                        .WithMany("Replies")
                        .HasForeignKey("ParentReplyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationUser", "Replier")
                        .WithMany("Replies")
                        .HasForeignKey("ReplierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentReply");

                    b.Navigation("Replier");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Reviews.Review", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationUser", "Reviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Slide", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Sliders.Slider", "Slider")
                        .WithMany("Slides")
                        .HasForeignKey("SliderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Slider");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.SocialMediaLink", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.About", null)
                        .WithMany("SocialMediaLinks")
                        .HasForeignKey("AboutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.SlideImageFile", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Slide", "Slide")
                        .WithOne("SlideImageFile")
                        .HasForeignKey("Shoppe.Domain.Entities.Files.SlideImageFile", "SlideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Slide");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Reactions.BlogReaction", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Blog", "Blog")
                        .WithMany("Reactions")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Reactions.ReplyReaction", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Replies.Reply", "Reply")
                        .WithMany("Reactions")
                        .HasForeignKey("ReplyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Reply");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Replies.BlogReply", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Blog", "Blog")
                        .WithMany("Replies")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Reviews.ProductReview", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.AboutContentImageFile", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.About", "About")
                        .WithMany("ContentImages")
                        .HasForeignKey("AboutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("About");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.BlogContentImageFile", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Blog", null)
                        .WithMany("ContentImages")
                        .HasForeignKey("BlogId");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.ProductImageFile", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Product", "Product")
                        .WithMany("ProductImageFiles")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.UserProfileImageFile", b =>
                {
                    b.HasOne("Shoppe.Domain.Entities.Identity.ApplicationUser", "User")
                        .WithMany("ProfilePictureFiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.About", b =>
                {
                    b.Navigation("ContentImages");

                    b.Navigation("SocialMediaLinks");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Basket", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Blog", b =>
                {
                    b.Navigation("ContentImages");

                    b.Navigation("Reactions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Coupon", b =>
                {
                    b.Navigation("Baskets");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Discount", b =>
                {
                    b.Navigation("CategoryMappings");

                    b.Navigation("ProductMappings");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Baskets");

                    b.Navigation("Blogs");

                    b.Navigation("ProfilePictureFiles");

                    b.Navigation("Reactions");

                    b.Navigation("Replies");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Order", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Product", b =>
                {
                    b.Navigation("DiscountMappings");

                    b.Navigation("ProductDetails")
                        .IsRequired();

                    b.Navigation("ProductImageFiles");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.ProductDetails", b =>
                {
                    b.Navigation("Dimension")
                        .IsRequired();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Replies.Reply", b =>
                {
                    b.Navigation("Reactions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Slide", b =>
                {
                    b.Navigation("SlideImageFile")
                        .IsRequired();
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Sliders.Slider", b =>
                {
                    b.Navigation("Slides");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.BillingAddress", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.ShippingAddress", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Categories.ProductCategory", b =>
                {
                    b.Navigation("DiscountMappings");
                });

            modelBuilder.Entity("Shoppe.Domain.Entities.Files.BlogContentImageFile", b =>
                {
                    b.Navigation("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
